version: '3'
services:
  ci:
    build: .
    environment:
      - CODECOV_TOKEN
      - CI=true
      - BUILDKITE
      - BUILDKITE_PARALLEL_JOB
      - BUILDKITE_PARALLEL_JOB_COUNT
      - BUILDKITE_PULL_REQUEST
      - BUILDKITE_PULL_REQUEST_REPO
      - GH_EMAIL
      - GH_TOKEN
      - GH_USERNAME
